# Generated by Django 3.1.4 on 2022-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_export_celery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportjob',
            options={'verbose_name_plural': 'Export Jobs'},
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='file',
            field=models.FileField(max_length=255, upload_to='django-export-celery-jobs/'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('STARTED', 'STARTED'), ('FAILURE', 'FAILURE')], default=None, max_length=25, null=True),
        ),
    ]
