# Generated by Django 3.1.4 on 2022-01-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_export_celery', '0002_auto_20220104_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportjob',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING')], default=None, max_length=25, null=True),
        ),
    ]
